apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress: 
  - type: Allow
    to:
      dnsName: openshift-squid.proxy.svc.cluster.local
  - type: Allow
    to:
      dnsName: bbc.com
  - type: Allow
    to:
      dnsName: www.bbc.com
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
